volumes:
  vaultwarden-data:
    name: vaultwarden-data

  tailscale-data:
    name: vaultwarden-tailscale-data

services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale_container
    hostname: vaultwarden-server
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json
      - TS_ACCEPT_DNS=true
      - TS_AUTH_ONCE=true
    volumes:
      - tailscale-data:/var/lib/tailscale
      - ./tailscale-config:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden_container
    restart: unless-stopped
    network_mode: "service:tailscale"
    environment:
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      PASSWORD_ITERATIONS: 2000000

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURITY: "starttls"
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_USERNAME}

    volumes:
      - vaultwarden-data:/data
    depends_on:
      - tailscale
